apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: .agents/skills/vendor
  contents:
  - path: juliusbrussee/caveman
    git:
      url: https://github.com/JuliusBrussee/caveman
      ref: origin/main
    includePaths:
    - skills/**
    - commands/**
    - LICENSE
  - path: mattpocock/skills
    git:
      url: https://github.com/mattpocock/skills
      ref: origin/main
    includePaths:
    - skills/**
    - LICENSE
  - path: mastra-ai/mastra
    git:
      url: https://github.com/mastra-ai/mastra
      ref: origin/main
    includePaths:
    - packages/evals/**
    - LICENSE
